# Generated by Django 5.0.4 on 2024-05-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
